services:
  - name: python-collaboration-platform
    source:
      type: git
    plan: starter
    environment:
      NODE_ENV: production
      MAX_CONCURRENT_USERS: 50
      MAX_ROOMS: 12
      MAX_USERS_PER_ROOM: 4
      WEBSOCKET_TIMEOUT: 300000
      AUTO_SAVE_INTERVAL: 180000
      CLEANUP_INTERVAL: 300000
      NODE_OPTIONS: "--max-old-space-size=384"
      # OpenAI AI助教配置 (需要在Zeabur控制台設定實際值)
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: gpt-3.5-turbo
      OPENAI_MAX_TOKENS: 2000
      OPENAI_TEMPERATURE: 0.3
      OPENAI_TIMEOUT: 30000
    build:
      commands:
        - npm ci
        - npm run build
    start:
      command: npm start
    port: 8080
    health_check:
      path: /api/status
      timeout_seconds: 30
      interval_seconds: 60
    resources:
      memory: "512Mi"
      cpu: "0.5"
    
databases:
  - name: mysql-db
    type: mysql
    version: "8.0"
    plan: free 